name: "Sphinx: Render docs"

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
    - uses: actions/checkout@v4
      with:
        persist-credentials: false
    - name: Clone Repo
      run: git clone https://github.com/langtech-bsc/rl_salamandra_alignment.git
    - name: Set Python Path
      run: export PYTHONPATH="$PWD/rl_salamandra_alignment/src/rl_salamandra_alignment"
    - name: Install Repo
      run: pip install -e rl_salamandra_alignment
    - name: dev stuff
      run: ls -a && pip freeze && pwd && which python && which python3
    - name: more dev stuff
      run: ls -a /usr/local/bin/ && echo "\n____\n" && ls -a /usr/bin/
    - name: try import
      run: python -c "import sys;print(sys.executable);import rl_salamandra_alignment;print('\n'.join(list(dir(rl_salamandra_alignment))));print(rl_salamandra_alignment.__version__);print('Done!')"
    - name: Build HTML
      uses: ammaraskar/sphinx-action@master
    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: html-docs
        path: docs/build/html/
    - name: Deploy
      uses: peaceiris/actions-gh-pages@v3
      if: github.ref == 'refs/heads/main'
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: docs/build/html